services:
    nats:
      container_name: nats
      restart: always
      image: nats:latest
      ports:
      - ${NATS_PORT}:${NATS_PORT}
      - ${NATS_PORT_2}:${NATS_PORT_2}
      networks:
        - microservice-network
        - database_pg

    postgres:
      container_name: postgres
      restart: always
      image: postgres:13.18
      ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
      - /tmp/data/postgres:/data/postgres
      networks:
        - microservice-network
        - database_pg
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    gateway-service:
      container_name: gateway-service
      ports:
        - ${GATEWAY_PORT}:${GATEWAY_PORT}
      build:
        context: .
        dockerfile: ./apps/server/gateway/Dockerfile
      networks:
        - microservice-network
        - database_pg
      environment: 
        NATS_URL: ${NATS_URL}
        NODE_ENV: ${NODE_ENV}
        GATEWAY_PORT: ${GATEWAY_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        - postgres
        - nats

    auth-service:
      container_name: auth-service
      build:
        context: .
        dockerfile: ./apps/server/auth/Dockerfile
      networks:
        - microservice-network
        - database_pg
      environment: 
        NATS_URL: ${NATS_URL}
        NODE_ENV: ${NODE_ENV}
        GATEWAY_PORT: ${GATEWAY_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        - postgres
        - nats
        
    chat-service:
      container_name: chat-service
      build:
        context: .
        dockerfile: ./apps/server/chat/Dockerfile
      networks:
        - microservice-network
        - database_pg
      environment: 
        NATS_URL: ${NATS_URL}
        NODE_ENV: ${NODE_ENV}
        GATEWAY_PORT: ${GATEWAY_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        - nats
        - postgres
    

networks:
  database_pg: {}
  microservice-network: {}