export const SOCKET_CHAT_PATTERN = Object.freeze({
  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',

  NEW_MESSAGE: 'NEW_MESSAGE',
  SEND_INTERACTION: 'SEND_INTERACTION',
  SEND_INTERACTION_FAIL: 'SEND_INTERACTION_FAIL',
  NEW_INTERACTION: 'NEW_INTERACTION',

  NEW_LAST_MESSAGE: 'NEW_LAST_MESSAGE',
});
