import { MICRO_SERVICE_NAMES } from '../microservice';

const CHAT_MODULES_NAME = Object.freeze({
  CHAT: `${MICRO_SERVICE_NAMES.CHAT_SERVICE}/CHAT_MODULE`,
  CHANNEL: `${MICRO_SERVICE_NAMES.CHAT_SERVICE}/CHANNEL_MODULE`,
  CONVERSATION:  `${MICRO_SERVICE_NAMES.CHAT_SERVICE}/CONVERSATION_MODULE`,
});

export const MESSAGE_PATTERN_CHAT = Object.freeze({
  SEND_MESSAGE: `${CHAT_MODULES_NAME.CHAT}/send-message`,
  DELETE: `${CHAT_MODULES_NAME.CHAT}/delete`,
  PAGING: `${CHAT_MODULES_NAME.CHAT}/paging`,

  INTERACTION: `${CHAT_MODULES_NAME.CHAT}/interaction`,
});

export const MESSAGE_PATTERN_CONVERSATION = Object.freeze({
  CREATE: `${CHAT_MODULES_NAME.CONVERSATION}/create`,
  DELETE: `${CHAT_MODULES_NAME.CONVERSATION}/delete`,
  PAGING: `${CHAT_MODULES_NAME.CONVERSATION}/paging`,
});

export const MESSAGE_PATTERN_CHANNEL = Object.freeze({
  CREATE: `${CHAT_MODULES_NAME.CHANNEL}/create`,
  JOIN: `${CHAT_MODULES_NAME.CHANNEL}/join`,
  LEAVE: `${CHAT_MODULES_NAME.CHANNEL}/leave`,
});
